import os

SECURITY_PASSWORD_SALT = os.getenv("SECURITY_SALT", "1am5u9erSEcr3T34")
SECURITY_REGISTERABLE = os.getenv("USER_REGISTRATION", True)
SECURITY_SEND_REGISTER_EMAIL = os.getenv("SECURITY_EMAIL", False)
